import { env } from '@/env.mjs';

export const siteConfig = {
  title: 'Golden State Web Design - Custom Websites for Small Businesses and Startups',
  description:
    'Golden State Web Design offers custom, hand-coded websites starting at $150/mo. No page builders or WordPress. Premium web development with lifetime updates & support.',
  keywords: [
    'web design',
    'web development',
    'digital marketing',
    'small business web design',
    'startup web design',
    'custom websites',
    'Golden State Web Design',
    'e-commerce web design',
    'responsive web design',
    'SEO services',
    'graphic design',
    'user experience design',
    'UI/UX design',
    'content management systems',
    'WordPress development',
    'mobile web design',
    'website maintenance',
    'website redesign',
    'branding',
    'web hosting',
    'domain registration',
    'online marketing',
    'social media marketing',
    'email marketing',
    'web analytics',
    'conversion optimization',
    'landing page design',
    'custom web applications',
    'full stack development',
    'frontend development',
    'backend development',
    'JavaScript',
    'HTML5',
    'CSS3',
    'React',
    'Next.js',
    'Node.js',
    'API integration',
    'e-commerce solutions',
    'online store design',
    'shopify development',
    'woocommerce development',
    'local SEO',
    'El Dorado Hills web design',
    'Folsom web design',
    'Granite Bay web design',
    'Cameron Park web design',
    'Shingle Springs web design',
    'Placerville web design',
    'Rescue web design',
    'Orangevale web design',
    'Fair Oaks web design',
    'Rancho Cordova web design',
    'Roseville web design',
    'Rocklin web design',
    'Lincoln web design',
    'Auburn web design',
    'Citrus Heights web design',
    'Carmichael web design',
    'Antelope web design',
    'Sacramento web design',
    'California web design',
    'West Coast web design',
    'professional web design',
    'affordable web design',
    'website optimization',
    'web consulting',
    'digital strategy',
    'web design company',
    'web design services',
    'creative web design',
    'website solutions',
    'online presence',
    'website performance',
    'custom website design',
    'web design agency',
    'modern web design',
    'website planning',
    'website strategy',
    'business website',
    'corporate web design',
    'portfolio website',
    'personal website',
    'artist website',
    'blog design',
    'website development',
    'website speed optimization',
    'security solutions',
    'SSL certificates',
    'ADA compliance',
    'accessibility',
    'interactive web design',
    'engaging web design',
    'visually appealing websites',
    'minimalist web design',
    'creative solutions',
    'user-friendly websites',
    'web innovation',
    'dynamic websites',
    'custom themes',
    'theme customization',
    'plugin development',
    'plugin customization',
    'web standards',
    'best web practices',
    'performance optimization',
    'scalable websites',
    'website audit',
    'website assessment',
    'web design trends',
    'cutting-edge web design',
    'future-proof websites',
  ],
  url: env.NEXT_PUBLIC_SITE_URL || 'https://goldenstatewebdesign.com',
  googleSiteVerificationId: env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION_ID || '',
};


export const structuredData = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "url": siteConfig.url,
  "name": siteConfig.title,
  "description": siteConfig.description,
  "potentialAction": {
    "@type": "SearchAction",
    "target": `${siteConfig.url}/search?q={search_term_string}`,
    "query-input": "required name=search_term_string"
  },
  "inLanguage": "en-US"
};